### ISSUE TITLE
Update custom Docker image or deprecate repo

### ISSUE THREAD

**Issue by GeckoEidechse** [joeyjoey1234/Pterodactyl_Egg_Titanfall_2_Northstar#1]
The [egg JSON file uses a custom Docker image](1https://github.com/joeyjoey1234/Pterodactyl_Egg_Titanfall_2_Northstar/blob/main/egg-titan-fall2.json#L13) based on [pg9182's northstar-dedicated](https://github.com/pg9182/northstar-dedicated) Docker image.

The issue is that this custom image hasn't been updated in 3 months and is running an older version that is now actively blocked from connecting to Northstar server browser, as such making the image in it's current state rather useless :P

**Comment by joeyjoey1234** [comment]
@GeckoEidechse thanks for pointing this out. :) totally forgot about this.
